social_post_linkedin.settings:
  type: config_object
  label: 'Social Post LinkedIn settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
